# Generated by Django 5.2.7 on 2026-01-13 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('loops', 'loops'), ('strings', 'strings'), ('arrays', 'arrays'), ('recursion', 'recursion'), ('conditionals', 'conditionals'), ('variables', 'variables')], max_length=64)),
                ('ef', models.FloatField(default=2.5)),
                ('interval', models.FloatField(default=0.0)),
                ('reps', models.IntegerField(default=0)),
                ('lapses', models.IntegerField(default=0)),
                ('due', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sm2_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'due'], name='ai_demo_top_user_id_8f9b7d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'topic'), name='uniq_user_topic_sm2')],
            },
        ),
    ]
