# Generated by Django 5.2.7 on 2026-01-13 11:35

from django.db import migrations
from django.utils import timezone

TOPICS = ["loops", "strings", "arrays", "recursion", "conditionals", "variables"]

def backfill(apps, schema_editor):
    TopicProgress = apps.get_model("ai_demo", "TopicProgress")
    User = apps.get_model("auth", "User")  # default Django user model

    now = timezone.now()
    rows = []
    for user in User.objects.all().only("id"):
        for topic in TOPICS:
            rows.append(TopicProgress(user_id=user.id, topic=topic, due=now))

    TopicProgress.objects.bulk_create(rows, ignore_conflicts=True)

def reverse_backfill(apps, schema_editor):
    TopicProgress = apps.get_model("ai_demo", "TopicProgress")
    TopicProgress.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_demo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill, reverse_backfill),
    ]
