# Generated by Django 5.2.7 on 2026-01-19 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_demo', '0002_backfill_topicprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_decay_applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_topic', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('print_basics', 'print_basics'), ('variables', 'variables'), ('primitive_data_types', 'primitive_data_types'), ('simple_operators', 'simple_operators'), ('while_loops', 'while_loops'), ('for_loops', 'for_loops'), ('conditionals', 'conditionals'), ('lists', 'lists'), ('strings_advanced', 'strings_advanced'), ('basic_edge_cases', 'basic_edge_cases'), ('dictionaries', 'dictionaries'), ('functions', 'functions'), ('all_loops_advanced', 'all_loops_advanced')], max_length=64)),
                ('proficiency', models.FloatField(default=0.0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_proficiencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'topic'], name='idx_user_topic_prof'), models.Index(fields=['user', 'proficiency'], name='idx_user_prof_value')],
                'constraints': [models.UniqueConstraint(fields=('user', 'topic'), name='uniq_user_topic_proficiency')],
            },
        ),
    ]
