# Generated by Django 5.2.7 on 2026-01-19 14:41

from django.db import migrations
from django.utils import timezone

TOPICS_LEVEL_1 = ["print_basics", "variables", "primitive_data_types", "simple_operators"]
TOPICS_LEVEL_2 = ["while_loops", "for_loops", "conditionals", "lists", "strings_advanced", "basic_edge_cases"]
TOPICS_LEVEL_3 = ["dictionaries", "functions", "all_loops_advanced"]
ALL_TOPICS = TOPICS_LEVEL_1 + TOPICS_LEVEL_2 + TOPICS_LEVEL_3

def backfill(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserLearningProfile = apps.get_model("ai_demo", "UserLearningProfile")
    TopicProficiency = apps.get_model("ai_demo", "TopicProficiency")

    now = timezone.now()

    # Profiles
    profiles = [UserLearningProfile(user_id=u.id, last_decay_applied_at=now) for u in User.objects.all().only("id")]
    UserLearningProfile.objects.bulk_create(profiles, ignore_conflicts=True)

    # Topic proficiency rows
    rows = []
    for u in User.objects.all().only("id"):
        for topic in ALL_TOPICS:
            rows.append(TopicProficiency(user_id=u.id, topic=topic, proficiency=0.0))
    TopicProficiency.objects.bulk_create(rows, ignore_conflicts=True)

def reverse_backfill(apps, schema_editor):
    TopicProficiency = apps.get_model("ai_demo", "TopicProficiency")
    UserLearningProfile = apps.get_model("ai_demo", "UserLearningProfile")
    TopicProficiency.objects.all().delete()
    UserLearningProfile.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('ai_demo', '0003_userlearningprofile_topicproficiency'),
    ]

    operations = [
        migrations.RunPython(backfill, reverse_backfill),
    ]
