# Generated by Django 5.0.1 on 2026-03-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_demo', '0005_add_usernotebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicproficiency',
            name='topic',
            field=models.CharField(choices=[('print_basics', 'print_basics'), ('variables', 'variables'), ('operators', 'operators'), ('strings', 'strings'), ('lists', 'lists'), ('conditionals', 'conditionals'), ('for_loops', 'for_loops'), ('while_loops', 'while_loops')], max_length=64),
        ),
    ]
