# Generated by Django 5.0.1 on 2026-04-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_demo', '0006_alter_topicproficiency_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlearningprofile',
            name='editor_theme',
            field=models.CharField(choices=[('vs-dark', 'Dark'), ('vs', 'Light')], default='vs-dark', max_length=10),
        ),
    ]
