# Generated by Django 5.2.7 on 2026-04-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_demo', '0007_userlearningprofile_editor_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicProgress',
        ),
    ]
